const model = {
    games: {
        cuphead: {
            name: "Cuphead",
            img_path: "img/cuphead-icon.png",
            view_function: "cupheadView()",
            guns: [
                {name: "Charge", img_path: "img/Cuphead/Guns/ChargeIcon.png"},
                {name: "Chaser", img_path: "img/Cuphead/Guns/ChaserIcon.png"},
                {name: "Converge", img_path: "img/Cuphead/Guns/ConvergeIcon.png"},
                {name: "Crackshot", img_path: "img/Cuphead/Guns/CrackshotIcon.png"},
                {name: "Lobber", img_path: "img/Cuphead/Guns/LobberIcon.png"},
                {name: "Peashooter", img_path: "img/Cuphead/Guns/PeashooterIcon.png"},
                {name: "Roundabout", img_path: "img/Cuphead/Guns/RoundaboutIcon.png"},
                {name: "Spread", img_path: "img/Cuphead/Guns/SpreadIcon.png"},
                {name: "Twist Up", img_path: "img/Cuphead/Guns/TwistUpIcon.png"},
            ],
            charms: [
                {name: "Astral Cookie", img_path: "img/Cuphead/Charms/AstralCookieIcon.png"},
                {name: "Coffee", img_path: "img/Cuphead/Charms/CoffeeIcon.png"},
                {name: "Divine Relic", img_path: "img/Cuphead/Charms/DivineRelicIcon.png"},
                {name: "Heart", img_path: "img/Cuphead/Charms/HeartIcon.png"},
                {name: "Twin Heart", img_path: "img/Cuphead/Charms/TwinHeartIcon.png"},
                {name: "Heart Ring", img_path: "img/Cuphead/Charms/HeartRingIcon.png"},
                {name: "P. Sugar", img_path: "img/Cuphead/Charms/PSugarIcon.png"},
                {name: "Smoke Bomb", img_path: "img/Cuphead/Charms/SmokeBombIcon.png"},
                {name: "Whetstone", img_path: "img/Cuphead/Charms/WhetstoneIcon.png"},
            ],
            super_arts: [
                {name: "1", img_path: "img/Cuphead/Super Arts/1.png"},
                {name: "2", img_path: "img/Cuphead/Super Arts/2.png"},
                {name: "3", img_path: "img/Cuphead/Super Arts/3.png"},
            ],
        },
        lol: {
            name: "League of Legends",
            img_path: "img/lol-icon.png",
            view_function: "LoLView()",
            champs: AllLeagueChamps,
            items: AllLeagueItems,
            summonerSpells: [
                {name: "Barrier", img_path: 'img/LoL/Summoner_Spells/Barrier.png'},
                {name: "Cleanse", img_path: 'img/LoL/Summoner_Spells/Cleanse.png'},
                {name: "Exhaust", img_path: 'img/LoL/Summoner_Spells/Exhaust.png'},
                {name: "Flash", img_path: 'img/LoL/Summoner_Spells/Flash.png'},
                {name: "Ghost", img_path: 'img/LoL/Summoner_Spells/Ghost.webp'},
                {name: "Heal", img_path: 'img/LoL/Summoner_Spells/Heal.png'},
                {name: "Ignite", img_path: 'img/LoL/Summoner_Spells/Ignite.png'},
                {name: "Smite", img_path: 'img/LoL/Summoner_Spells/Smite.png'},
                {name: "Teleport", img_path: 'img/LoL/Summoner_Spells/Teleport.png'},
            ],
            roles: [
                {name: "Top", img_path: "img/LoL/Roles/Top.png"},
                {name: "Jungle", img_path: "img/LoL/Roles/Jungle.png"},
                {name: "Mid", img_path: "img/LoL/Roles/Mid.png"},
                {name: "ADC", img_path: "img/LoL/Roles/Bot.png"},
                {name: "Support", img_path: "img/LoL/Roles/Support.png"},
            ],
            itemsPicked: []
        },
    },
    view: document.getElementById("randomizerContent"),
    menu: document.getElementById("menu-dropdown"),
    menulist: document.getElementById("menuGameList"),
};